name: Build and Package

env:
  OUTPUT: ./Output
  CONFIG: Release

on:
  push:
    tags:
      - "release/*"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Get Version 
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/release\//}
      shell: bash
      
    - uses: actions/checkout@v2  
      
    - name: Setup .net core
      uses: actions/setup-dotnet@v1.4.0
      
    - name: Setup UmbPack
      run: dotnet tool install Umbraco.Tools.Packages --global
      
    - name: Restore dependencies
      run: dotnet restore ./source/InboundLinkErrors.sln
      
    - name: Build
      run: dotnet build ./source/InboundLinkErrors.sln --configuration ${{ env.CONFIG }} --no-restore
      
    - name: Create NuGet package file for Core
      run: dotnet pack ./source/InboundLinkErrors.Core/InboundLinkErrors.Core.csproj -c ${{ env.CONFIG }} --no-build -o ${{ env.OUTPUT }} /p:version=${{ steps.get_version.outputs.VERSION }}
    
    - name: Create NuGet package file for Backoffice
      run: dotnet pack ./source/InboundLinkErrors/InboundLinkErrors.csproj -c ${{ env.CONFIG }} --no-build -o ${{ env.OUTPUT }} /p:version=${{ steps.get_version.outputs.VERSION }}
   
#    - name: Push packages to NuGet
#      run: dotnet nuget push "**/*.nupkg" -k ${{ secrets.NUGET_DEPLOY_KEY }} -s https://api.nuget.org/v3/index.json
 
#    - name: Create Umbraco package file
#      run: UmbPack pack ./source/package.xml -o ${{ env.OUTPUT }} -v ${{ steps.get_version.outputs.VERSION }}

    - name: upload-artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build-Results-${{ steps.get_version.outputs.VERSION }}
        path: ${{ env.OUTPUT }}/**/*
